#!/usr/bin/env bash
# Phantom CLI - Configuration management
# Simple KEY=VALUE format (bash-sourceable)

# Initialize config directory and default config
phantom_config_init() {
    if [ ! -d "$PHANTOM_DIR" ]; then
        mkdir -p "$PHANTOM_DIR"
        log_info "Created $PHANTOM_DIR"
    fi

    if [ ! -f "$PHANTOM_CONFIG" ]; then
        cat > "$PHANTOM_CONFIG" <<'DEFAULTS'
# Phantom CLI Configuration
# Generated by: phantom setup

# Server settings
SERVER_HOST=
SERVER_PORT=22
HTTP_PROXY_PORT=8080

# Authentication
SSH_KEY=~/.ssh/id_rsa
API_KEY=

# Options
AUTO_CONNECT=true
AUTO_RECONNECT=true

# Connection mode: "tunnel" (SSH tunnel) or "direct" (connect to VPS directly)
CONNECTION_MODE=direct
DEFAULTS
        log_info "Created default config at $PHANTOM_CONFIG"
    fi
}

# Read a value from config
# Usage: phantom_config_get KEY
phantom_config_get() {
    local key="$1"

    if [ ! -f "$PHANTOM_CONFIG" ]; then
        return 1
    fi

    local value
    value=$(grep -E "^${key}=" "$PHANTOM_CONFIG" 2>/dev/null | tail -1 | cut -d'=' -f2-)

    if [ -z "$value" ]; then
        return 1
    fi

    # Expand tilde in paths
    echo "${value/#\~/$HOME}"
}

# Write a value to config
# Usage: phantom_config_set KEY VALUE
phantom_config_set() {
    local key="$1"
    local value="$2"

    phantom_config_init

    if grep -qE "^${key}=" "$PHANTOM_CONFIG" 2>/dev/null; then
        # Update existing key (macOS/BSD sed compatible)
        sed -i '' "s|^${key}=.*|${key}=${value}|" "$PHANTOM_CONFIG"
    else
        # Append new key
        echo "${key}=${value}" >> "$PHANTOM_CONFIG"
    fi
}
